# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2c2d201b-dc53-4bc4-828d-53adbfda9bd0";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-a7426a00-3f72-4e06-8d8c-2d9c5c1aab73".device = "/dev/disk/by-uuid/a7426a00-3f72-4e06-8d8c-2d9c5c1aab73";
  boot.initrd.luks.devices."luks-fb7428af-10d5-4c4b-a326-9ce64098b3c5".device = "/dev/disk/by-uuid/fb7428af-10d5-4c4b-a326-9ce64098b3c5";


  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8DA8-5DA4";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/Plus" =
    { device = "/dev/disk/by-uuid/ede82f73-c4ea-4b0b-b215-b4dad62e1d6c";
      fsType = "ext4";
    };

  fileSystems."/mnt/Extra" =
    { device = "/dev/disk/by-uuid/617efd75-dac6-4626-8022-314b35ae4492";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/1fc0a353-a473-4096-a0dd-a18524edf88c"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp36s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
